name: Continuous Integration

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    services:
      product_db:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: products
        ports:
          - 5432:5432
      order_db:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: orders
        ports:
          - 5433:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r backend/product_service/requirements.txt
        pip install -r backend/order_service/requirements.txt
        pip install pytest

    - name: Run product service tests
      working-directory: backend/product_service
      env:
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        POSTGRES_DB: products
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      run: pytest tests/ -v

    - name: Run order service tests
      working-directory: backend/order_service
      env:
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5433
        POSTGRES_DB: orders
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      run: pytest tests/ -v

  frontend-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      working-directory: frontend
      run: npm install

    - name: Build frontend
      working-directory: frontend
      run: npm run build